### ISSUE TITLE
Feature Suggestion:  Set default path for saving token images

### ISSUE THREAD

**Issue by git-kor-av** [ChadKeating/rolladvantage-token-stamp-2-foundry#2]
In order to help keep the Foundry Data folder structured, I have a specific folder for tokens.  It would be helpful if there were module settings that allowed you to chose the path where this module saves token images.

**Comment by ChadKeating** [comment]
Yeah, good idea!

**Comment by ChadKeating** [comment]
This is now added in the module settings menu
